import { useEffect } from "react";
import { amountInWords, METHODS, rupees } from "../data/money.js";
import { logoUrl } from "../data/api.js";
import { gradeLabel } from "./PersonCard.jsx";
import Icon from "./Icon.jsx";

const fmt = (d) => new Date(d).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });

// Printable fee receipt. `dues` are the student's dues (to name what was paid).
export default function Receipt({ school, person, payment, dues, onClose }) {
  useEffect(() => {
    const onKey = (e) => e.key === "Escape" && onClose();
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  const dueById = new Map(dues.map((d) => [d.id, d]));
  const lines = (payment.allocations ?? []).map((a) => ({ ...a, due: dueById.get(a.invoice_id) }));
  const allocated = lines.reduce((s, l) => s + Number(l.amount), 0);
  const credit = Number(payment.amount) - allocated;
  const address = [school.address, school.city, school.state, school.pincode].filter(Boolean).join(", ");

  return (
    <div className="modal-backdrop receipt-backdrop" onClick={onClose}>
      <section className="modal receipt-modal" onClick={(e) => e.stopPropagation()} aria-label="Fee receipt">
        <div className="receipt-tools no-print">
          <button className="btn btn-primary btn-sm" onClick={() => window.print()}>
            <Icon name="file" />
            Print / Save PDF
          </button>
          <button className="btn-icon" onClick={onClose} aria-label="Close">
            <Icon name="x" size={18} />
          </button>
        </div>

        <article className="receipt">
          <header className="receipt-head">
            {school.logo_path && <img src={logoUrl(school.logo_path)} alt="" />}
            <div>
              <h2>{school.name}</h2>
              {address && <p>{address}</p>}
              {(school.phone || school.email) && <p>{[school.phone, school.email].filter(Boolean).join(" · ")}</p>}
            </div>
          </header>

          <div className="receipt-title">
            <span>Fee receipt</span>
            {payment.status === "cancelled" && <span className="badge badge-danger">Cancelled</span>}
          </div>

          <dl className="receipt-meta">
            <div>
              <dt>Receipt no.</dt>
              <dd>{payment.receipt_no}</dd>
            </div>
            <div>
              <dt>Date</dt>
              <dd>{fmt(payment.paid_on)}</dd>
            </div>
            <div>
              <dt>Student</dt>
              <dd>{person.name}</dd>
            </div>
            <div>
              <dt>Admission no.</dt>
              <dd>{person.admission_no}</dd>
            </div>
            <div>
              <dt>Class</dt>
              <dd>{[gradeLabel(person.class), person.section].filter(Boolean).join(" · ")}</dd>
            </div>
            <div>
              <dt>Paid by</dt>
              <dd>
                {METHODS[payment.method]}
                {payment.reference ? ` (${payment.reference})` : ""}
              </dd>
            </div>
          </dl>

          <table className="receipt-lines">
            <thead>
              <tr>
                <th>Towards</th>
                <th>Amount</th>
              </tr>
            </thead>
            <tbody>
              {lines.map((l) => (
                <tr key={l.invoice_id}>
                  <td>{l.due ? `${l.due.head_name ?? "Fee"} · ${l.due.label}` : "Fee"}</td>
                  <td>{rupees(l.amount)}</td>
                </tr>
              ))}
              {credit > 0.009 && (
                <tr>
                  <td>Advance (kept as credit)</td>
                  <td>{rupees(credit)}</td>
                </tr>
              )}
            </tbody>
            <tfoot>
              <tr>
                <th>Total received</th>
                <th>{rupees(payment.amount)}</th>
              </tr>
            </tfoot>
          </table>

          <p className="receipt-words">{amountInWords(payment.amount)}</p>
          {payment.note && <p className="receipt-note">Note: {payment.note}</p>}

          <footer className="receipt-foot">
            <span>Received by {payment.received_by ?? "school office"}</span>
            <span>Generated by Godview</span>
          </footer>
        </article>
      </section>
    </div>
  );
}
